# frozen_string_literal: true

# One elevator of a report draft. A report identifies several equipments
# ("Ascensor A", "Ascensor B") and each finding may point at one of them.
#
# `label` is the only required column — the visible identifier the certifier
# uses out loud. Every technical spec is optional and bounded to what the real
# report of section 3.1 records; Danebo never derives or fills any of them
# (fixed rule 1), and nothing is asked during dictation (fixed rule 4).
#
# A report may legitimately have zero equipments while it is being captured.
class CreateReportEquipments < ActiveRecord::Migration[8.1]
  def change
    create_table :report_equipments do |t|
      t.references :certification_report, null: false, foreign_key: true, index: false
      t.references :account, null: false, foreign_key: true
      t.string  :label, null: false
      t.integer :position, null: false, default: 0

      # Optional technical characteristics, section 3.1. Free text / plain
      # numbers: no unit conversion, no inference, no defaults.
      t.string  :machine_room
      t.string  :drive_type
      t.string  :door_type
      t.integer :boardings_count
      t.integer :landings_count
      t.string  :traction_cables
      t.decimal :speed_mps, precision: 6, scale: 3
      t.integer :rated_load_kg
      t.integer :capacity_persons
      t.date    :last_maintenance_date

      t.timestamps
    end

    # Named explicitly: Rails hashes autogenerated names past 63 characters
    # (Fase 0, hallazgo 5). Covers "equipments of this report" and their order.
    add_index :report_equipments,
              [ :certification_report_id, :position ],
              name: "idx_report_equipments_report_position"
  end
end
